Repository milieuinfo/webcomponent-vl-ui-form-validation, pull requests merged in 2020-04, with the labels that each got.

#25 Update dependency vl-ui-util to v5.1.5
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#30 Introductie rijksregisternummer modulo validatie
  lib/form-validation.js
  src/vl-form-validation.js
  test/e2e/form-validation.test.js
Labels: enhancement

#31 Update vl-ui-util
  .mocharc.js
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
Labels: chore
